package com.dev.pariisa.dota2.dependencies

object Versions {

    const val kotlin = "1.9.0"
    const val gradle = "8.0"
    const val gradlePlugin = "8.1.2"
    const val androidLibrary = "7.2.2"
    const val kotlinJvm = "1.7.10"
    const val kt_lint = "0.37.2"
    const val coreKtx = "1.12.0"
    const val appCompat = "1.6.1"
    const val material = "1.10.0"
    const val constraintLayout = "2.1.4"
    const val navigationComponent = "2.7.4"
    const val recyclerView = "1.3.2"
    const val cardView = "1.0.0"
    const val preference = "1.0.0"
    const val pagingIndicatorView = "1.0.3"
    const val legacy = "1.0.0"
    const val multidex = "2.0.1"
    const val rxJava = "2.2.12"
    const val rxJavaAndroid = "2.1.1"

    const val coroutines = "1.7.3"
    const val coroutinesAdapter = "0.9.2"
    const val gradleVersion = "8.0"
    const val hilt = "2.48.1"
    const val hiltViewModel = "1.0.0"
    const val room = "2.6.0"
    const val dagger = "2.48.1"
    const val okHttp = "4.11.0"
    const val gson = "2.10.1"
    const val retrofit = "2.9.0"
    const val stetho = "1.6.0"
    const val glide = "4.16.0"
    const val junit = "4.13.2"
    const val extJunit = "1.1.5"
    const val testRunner = "1.2.0"
    const val espresso = "3.5.1"
    const val mockitoKotlin = "5.1.0"
    const val fragment = "1.6.1"
    const val lifeCycle = "2.6.2"
    const val paging = "3.2.1"
    const val kotlinConverter = "0.8.0"
    const val jsonSerialization = "1.3.3"
    const val picasso = "2.8"
    const val coil = "2.4.0"
    const val dataStore = "1.0.0"
    const val coreSplash = "1.0.0"
    const val timber = "5.0.1"
}